### ISSUE TITLE
Can't select booklet binding

### ISSUE THREAD

**Issue by SYSKYMAN** [yonixw/MangaPrinter#11]
Hi I don't know  why but I can't select booklet binding. Is it locked by default or I doing something wrong. If not this issue, program would be the best.

Small issues:
Would be very good if added pages be without the text. Extra pages in the middle of the chapter don't need to have text. And extra pages in the end or in front of the chapter can have text, but it would be better if text say what's gonna be next chapter and/or when chapter ends. But the most useful would be customisable text when you can to choose best suited phrase to use.

**Comment by yonixw** [comment]
Hi, currently booklet isn't supported. Good to know there is interest in that feature, so I will make time to develop it.

I will also create new issue for:
> most useful would be customisable text

**Comment by yonixw** [comment]
Hi, I had time to work on this project and now booklet binding is available, and also many configurations such as page text.

Here is my short video explaining configurations:

https://youtu.be/ACURi1TLLTU
