### ISSUE TITLE
about picture frames

### ISSUE THREAD

**Issue by necrokamo** [yonixw/MangaPrinter#17]
Hello, is there any possibility to have the option to disable the black frames that are around the images when they are exported?

**Comment by yonixw** [comment]
I can do some checkbox for it. I'll put it on the roadmap

**Comment by yonixw** [comment]
Hi, I had time to work on this project and now configurations such as add borders exists.

Here is my short video explaining configurations:

https://youtu.be/ACURi1TLLTU
