### ISSUE TITLE
Better Page width handling

### ISSUE THREAD

**Issue by selfcac** [yonixw/MangaPrinter#2]
**Problem:**

- Some pages have single page with little more white on the side resulting in W+1px and becoming  a double page.
- Some chapters in high quality has absolute WxH way higher... like 1337x1925.

**A solution:**

- Use ratio W/H instead of hardcore W in px
- Make a dialog to show histogram of all ratios to make a cut based on current chapters.

**Comment by yonixw** [comment]
Solved with dialog of ratio histogram ... in v1.2
