### ISSUE TITLE
Export to pdf turns all pages black and white

### ISSUE THREAD

**Issue by ghost** [yonixw/MangaPrinter#6]
Exporting full color or mixed color/bw mangas turns them all into b/w. Is this a bug or an intended function?
What do I need to do to make it work?

**Comment by yonixw** [comment]
Hmmm given that the purpose was printing, I convert all images to 8-bit color (grayscale, but actually 16 bit in .NET). This is the intended function, and also a feature as it make the final PDF smaller. Colorful PDFs has been too big and actually was not printable in some industrial printers,

The relevant code can be found here:
https://github.com/yonixw/MangaPrinter/blob/master/MangaPrinter.Core/TemplateBuilders/DuplexTemplates.cs#L76

Do you have a use case for not converting them? might add a check box.

**Comment by ghost** [comment]
I have a few one shots which I want to compile into a single volume. I previously put them through waifu2x gui so I'm looking for the best possible quality when I print them. If a checkbox could be added that would be wonderful. Thanks for the help!

**Comment by yonixw** [comment]
Made a release with this feature: 
https://github.com/yonixw/MangaPrinter/releases/tag/v1.4

How it looks:
![image](https://user-images.githubusercontent.com/5826209/103570730-4ef96d00-4ed2-11eb-81a9-83081857cc06.png)

BTW @yaoberh, how did you run MangaPrinter? did you mange to run it on linux?

**Comment by ghost** [comment]
Awesome!! Thanks a lot. I asked a friend who's running windows. Didn't manage to make it work on linux, either with playonlinux nor double clicking the exe and letting wine do the execution. It crashes as soon as you press add files.
